# Generated by Django 5.2.13 on 2026-04-12 09:05

import django.db.models.deletion
import documents.models
import documents.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[documents.validators.validate_document_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
                    models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
                    models.Index(fields=['uploaded_by', 'created_at'], name='documents_d_uploade_28af31_idx'),
                ],
            },
        ),
    ]
