# Generated by Django 5.2.13 on 2026-04-12 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.unit'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['department', 'created_at'], name='documents_d_departm_33c2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['unit', 'created_at'], name='documents_d_unit_id_face9b_idx'),
        ),
    ]
