# Generated by Django 5.2.13 on 2026-04-12 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0002_document_department_document_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ocr_status', 'created_at'], name='documents_d_ocr_sta_fb9903_idx'),
        ),
    ]
