# Generated by Django 5.2.13 on 2026-04-12 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='documents.document')),
            ],
            options={
                'verbose_name': 'OCR job',
                'verbose_name_plural': 'OCR jobs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='documents_o_status_2f0170_idx'), models.Index(fields=['document', 'status', 'created_at'], name='documents_o_documen_3d0065_idx')],
            },
        ),
    ]
