# Generated by Django 5.2.13 on 2026-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_storage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['extracted_date', 'created_at'], name='documents_d_extract_6b9f9f_idx'),
        ),
    ]
