# Generated by Django 5.2.13 on 2026-04-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_extracted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='ready', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['processing_status', 'created_at'], name='documents_d_process_17954c_idx'),
        ),
    ]
