# Generated by Django 5.2.13 on 2026-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='headings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata_source',
            field=models.CharField(choices=[('heuristic', 'OCR heuristic'), ('ai', 'AI extraction')], default='heuristic', max_length=20),
        ),
    ]
